### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AbdoulNuru** [swdotcom/swdc-vscode-100-days-of-code#11]
- Issue Type: `Performance`
- Extension Name: `swdc-100-days-of-code`
- Extension Version: `1.0.5`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.48.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\abdounuru.niyigena.GTBank.000.001.002.003.004.005\softwaredotcom.swdc-100-days-of-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by brettmstevens7** [comment]
@AbdoulNuru can you attach your file? Webviews may cause a spike in CPU, which might be the cause, but we'll take a look.

**Comment by AbdoulNuru** [comment]
> @AbdoulNuru can you attach your file? Webviews may cause a spike in CPU, which might be the cause, but we'll take a look.

@brettmstevens7 The issue is now resolved.
