### ISSUE TITLE
Integration with code-time extension resulting in duplication of logs

### ISSUE THREAD

**Issue by DemonDaddy22** [swdotcom/swdc-vscode-100-days-of-code#17]
This has happened to me a couple of times now, although I try to add logs myself, sometimes when I forget to log my work and the automated logs (created at midnight) are generated, they are sort of getting replicated for a day. There's no option to delete such logs, so what happens is, even if I have been coding consistently, the dashboard starts showing gaps because of these duplicated logs.

<img width="861" alt="Screenshot 2020-08-31 at 11 35 31 PM" src="https://user-images.githubusercontent.com/39908472/91752490-107e3980-ebe4-11ea-8cae-5040d02fcbcc.png">

**Comment by dhatGuy** [comment]
I am experiencing same issue too. Logs are being added automatically.

**Comment by brettmstevens7** [comment]
Thanks, working on a fix and a feature to delete a log.

**Comment by javila35** [comment]
Getting this error as well. Thanks for working on a fix!

**Comment by deepak-vasalamarri** [comment]
> Thanks, working on a fix and a feature to delete a log.

Thanks for working on a feature to delete a log. My logs are messed up due to issue mentioned in https://github.com/swdotcom/swdc-vscode-100-days-of-code/issues/24 . To clean the logs i need a delete feature ASAP.

**Comment by brettmstevens7** [comment]
Hey all, sorry for the bug. The duplicate logs have been deleted and a new plugin version has been fixed. This should be fixed the next time you restart VS Code.

**Comment by DemonDaddy22** [comment]
There seems to be some issue, the extension is not correctly picking up the system date.

<img width="918" alt="Screenshot 2020-09-17 at 10 18 16 AM" src="https://user-images.githubusercontent.com/39908472/93421583-5e2abf80-f8cf-11ea-9da4-865308913fcc.png">
