### ISSUE TITLE
100 Days of Code tab is empty in vscode

### ISSUE THREAD

**Issue by dhatGuy** [swdotcom/swdc-vscode-100-days-of-code#18]
No way for me to use the extension because there's no content in the tab

![Screenshot (21)](https://user-images.githubusercontent.com/51405947/91782371-bf2a7600-ebf4-11ea-9bcd-bf2f4db876f7.png)

**Comment by brettmstevens7** [comment]
@dhatGuy can you check your console to see if there's an error?

**Comment by dhatGuy** [comment]
```
abstractExtensionService.ts:411 Activating extension 'softwaredotcom.swdc-100-days-of-code' failed: Cannot convert undefined or null to object.
_logMessageInConsole @ abstractExtensionService.ts:411
_logOrShowMessage @ abstractExtensionService.ts:425
$onExtensionActivationError @ mainThreadExtensionService.ts:70
_doInvokeHandler @ rpcProtocol.ts:409
_invokeHandler @ rpcProtocol.ts:394
_receiveRequest @ rpcProtocol.ts:310
_receiveOneMessage @ rpcProtocol.ts:237
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:463
_receiveMessage @ ipc.net.ts:747
(anonymous) @ ipc.net.ts:602
fire @ event.ts:587
acceptChunk @ ipc.net.ts:240
(anonymous) @ ipc.net.ts:201
t @ ipc.net.ts:29
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

```

**Comment by brettmstevens7** [comment]
Thanks @dhatGuy, we'll look into it. Just to confirm, there aren't any other errors in the console, just this one?

**Comment by dhatGuy** [comment]
There are but not related to 100 Days of Code extension.
I got these too before getting the error I sent earlier. Not sure if it will help.

```
[Extension Host] Loaded softwaredotcom.swdc-100-days-of-code v1.0.6
[Extension Host] File not found: C:\Users\odunsi\.software\logsPayload.json
```

**Comment by brettmstevens7** [comment]
Thanks, exactly what I needed.

**Comment by AugustBemsen** [comment]
> No way for me to use the extension because there's no content in the tab
> 
> ![Screenshot (21)](https://user-images.githubusercontent.com/51405947/91782371-bf2a7600-ebf4-11ea-9bcd-bf2f4db876f7.png)

Please what theme are you using?

**Comment by dhatGuy** [comment]
> 
> 
> > No way for me to use the extension because there's no content in the tab
> > ![Screenshot (21)](https://user-images.githubusercontent.com/51405947/91782371-bf2a7600-ebf4-11ea-9bcd-bf2f4db876f7.png)
> 
> Please what theme are you using?

[Aurora X](marketplace.visualstudio.com/items?itemName=marqu3s.aurora-x)

**Comment by BrianLeip** [comment]
Same problem on my side - no options available in  the 100 DAYS OF CODE section

![image](https://user-images.githubusercontent.com/16980550/92037885-5394f580-ed27-11ea-822b-c6752b1c7d45.png)

**Comment by dhatGuy** [comment]
I noticed this happens after logging in into my Code time account.
After logging in, I get this.
![Screenshot (22)](https://user-images.githubusercontent.com/51405947/92088292-9527ae00-edc4-11ea-9100-3b1eee3d2a20.png)

With this error
```
c:\Users\odunsi\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.6\out\utils\LogsDbUtils.js:50
    if (Object.keys(payloadData).length < 4) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.checkLogsPayload (c:\Users\odunsi\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.6\out\utils\LogsDbUtils.js:50:16)
    at Timeout._onTimeout (c:\Users\odunsi\.vscode\extensions\softwaredotcom.swdc-100-days-of-code-1.0.6\out\extension.js:169:27)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}
```

**Comment by Gaotianhe** [comment]
My aim: run 100 Days of Code on my WSL: Ubuntu-18.04

```
Env:
OS version: Win10 1903
OS build: 18362.476
wsl1: Ubuntu-18.04
#Below is about VS code
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

#Below is about VS code extension
100 Days of Code version: 1.0.11
Code Time version: 2.3.11
```

However, I encounter problems.

1. Code Time cannot run in WSL alone, I had install and reinstall many times, finally I did it: disable local win10 env, run only on wsl: Ubuntu-18.04.

2. A empty `100 Days of Code` tab. Although I both install `code time` and `100 Days of Code`, I can't see normal `100 Days of Code` tab. Also, use it normally in local win10 env. I find isssues in [swdotcom/swdc-vscode](https://github.com/swdotcom/swdc-vscode), find it: `Editor tracking doesn´t work through vscode WSL instance` https://github.com/swdotcom/swdc-vscode/issues/87. I tried these ways and none of them worked.
