### ISSUE TITLE
Can't find Logs and Milestones Tabs

### ISSUE THREAD

**Issue by AugustBemsen** [swdotcom/swdc-vscode-100-days-of-code#19]
`Command '100 Days of Code: View Milestones' resulted in an error (command 'DoC.viewMilestones' not found)`
Got the error when i manually tried running the command
And 100days of code Section is empty 
![image](https://user-images.githubusercontent.com/54921134/91916491-2e679f00-ecb5-11ea-89db-fb923a0b8e36.png)

**Comment by brettmstevens7** [comment]
@AugustBemsen a fix was just pushed in 1.0.7 - can you try this version? Thank you!
