### ISSUE TITLE
Publish on open-vsx

### ISSUE THREAD

**Issue by HansUXdev** [swdotcom/swdc-vscode-100-days-of-code#20]
Do you mind if I publish this on open-vsx?
Under the Apache License I can, but I still want to ask.
I already helped publish the music app:
https://open-vsx.org/extension/softwaredotcom/music-time

If you @ me on any major updates, I can bump the versions.

**Comment by brettmstevens7** [comment]
@HansUXdev - yes you can publish. Thanks!
