### ISSUE TITLE
Several achievements in one day

### ISSUE THREAD

**Issue by Stegur** [swdotcom/swdc-vscode-100-days-of-code#24]
I think something went wrong today.

![image](https://user-images.githubusercontent.com/2816856/92391208-e5847000-f124-11ea-8d56-3f864b8b30e2.png)

![image](https://user-images.githubusercontent.com/2816856/92391246-fc2ac700-f124-11ea-8b92-d3d80c7e5752.png)

VSCode 1.48.2, Windows 10

**Comment by tarasis** [comment]
I had that exact hiccup earlier today (first time using the plugin), where it kept increasing days of coding. So I’m now at Level infinity for days Of coding achievements, with currently 139 day logs.

VSCode 1.48.2 on macOS 10.15.6

**Comment by brettmstevens7** [comment]
Hey @Stegur and @tarasis - sorry for the bug. The duplicate logs have been deleted and a new plugin version has been fixed. This should be fixed the next time you restart VS Code.
