### ISSUE TITLE
Achieved 100 day certificate after day 28

### ISSUE THREAD

**Issue by RP-Coding** [swdotcom/swdc-vscode-100-days-of-code#28]
Hi, I have achieved my 100 days coding achievement after only day 28.  The extension appears to be creating multiple logs per day which may be contributing to the issue.  I have attached a screenshot, hopefully this will help.

Thanks for the extension, it is really appreciated and really helps to motivate me.
<img width="700" alt="Duplicate logs" src="https://user-images.githubusercontent.com/53057939/93003010-fd982d00-f532-11ea-998a-1e2d5f9ed81c.PNG">

**Comment by angel-codes** [comment]
Yeah, I have the same problem. I was going on day 10 and out of nowhere, it went up to day 1000. Does anyone know if I can reset my data?
![image](https://user-images.githubusercontent.com/65056245/93133613-22101880-f69d-11ea-9529-65fe21d601c4.png)

**Comment by brettmstevens7** [comment]
Hey @RP-Coding and @angel-codes - sorry for the bug. We just pushed an update. Please make sure you have the latest version of the plugin. This should be fixed the next time you restart VS Code.

**Comment by RP-Coding** [comment]
HI Brett, thanks for this.  The duplicate logs have now been deleted but it has not renumbered the Day count (ie my log thinks I am on Day 117 rather than Day 32).  Is there any way to fix this?

Thanks so much for responding to this issue so quickly!

**Comment by RP-Coding** [comment]
![Numbering issue](https://user-images.githubusercontent.com/53057939/93389702-6bf72b00-f864-11ea-91ff-54a65370fb79.jpg)

Here is a picture for your reference.  Thanks!

**Comment by brettmstevens7** [comment]
@RP-Coding can you send an email to support@software.com with the email that you used to register? Some of the days are out of order, so I wonder if there's another bug with your data. Thanks.

**Comment by RP-Coding** [comment]
Thanks Brett, I will do.
