### ISSUE TITLE
README.md opens every time opening a new project

### ISSUE THREAD

**Issue by ronilaukkarinen** [swdotcom/swdc-vscode-100-days-of-code#29]
Press shift + cmd + N (macOS), open a project, see README.md popping up. Annoying.

**Comment by volkoff-pro** [comment]
Same result, if I open new project/restart VS Code - README.md is opened.

**Comment by xavluiz** [comment]
Thank you for the update on this. We've fixed that issue and published v1.0.11 to the markeplace.
Regards.

**Comment by ronilaukkarinen** [comment]
Seems to work now. Thanks.
