### ISSUE TITLE
Confused about milestone "Please Comment"

### ISSUE THREAD

**Issue by AugustasV** [swdotcom/swdc-vscode-100-days-of-code#6]
I am confused. There is milestone "Please Comment", but it's written 10 shares.
![image](https://user-images.githubusercontent.com/7377334/89617874-a4820d00-d893-11ea-8733-1b32b3da8780.png)
It should be like that or it's a mistake?

**Comment by dillon-sftw** [comment]
Hey Augustas. Thanks for the feedback. "Please Comment" is the title of this particular milestone and in no way affects how to unlock it. The idea of the title was to pay homage to "Please like, comment, and subscribe" that many YouTubers say at the end of their videos. You will unlock the milestone after sharing 10 times within the plugin.
